version: '3.9'

services:
  postgres:
    image: "postgres:14-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "driver-app"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

networks:
  postgres-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data:
